// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3bTmsyCGGjuXMWHLUOr_TPEC99SRt-tw',
    appId: '1:659074825801:web:792fdf9448f74cf25e0998',
    messagingSenderId: '659074825801',
    projectId: 'websitefirebase-8ee0b',
    authDomain: 'websitefirebase-8ee0b.firebaseapp.com',
    storageBucket: 'websitefirebase-8ee0b.appspot.com',
    measurementId: 'G-01ZE62TRWN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP0Y2vJcc3fhl2R7-dMwF2WKFLF69-Ftk',
    appId: '1:659074825801:android:bfe1504f5f711e895e0998',
    messagingSenderId: '659074825801',
    projectId: 'websitefirebase-8ee0b',
    storageBucket: 'websitefirebase-8ee0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8-XO1EUxk_BW64awV8XqOY1YpYL5YCSc',
    appId: '1:659074825801:ios:5946b888a42dba3b5e0998',
    messagingSenderId: '659074825801',
    projectId: 'websitefirebase-8ee0b',
    storageBucket: 'websitefirebase-8ee0b.appspot.com',
    iosBundleId: 'com.example.personalwebpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8-XO1EUxk_BW64awV8XqOY1YpYL5YCSc',
    appId: '1:659074825801:ios:5946b888a42dba3b5e0998',
    messagingSenderId: '659074825801',
    projectId: 'websitefirebase-8ee0b',
    storageBucket: 'websitefirebase-8ee0b.appspot.com',
    iosBundleId: 'com.example.personalwebpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3bTmsyCGGjuXMWHLUOr_TPEC99SRt-tw',
    appId: '1:659074825801:web:ba2e1acce0863dbe5e0998',
    messagingSenderId: '659074825801',
    projectId: 'websitefirebase-8ee0b',
    authDomain: 'websitefirebase-8ee0b.firebaseapp.com',
    storageBucket: 'websitefirebase-8ee0b.appspot.com',
    measurementId: 'G-6D149LW1TW',
  );

}